/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpcjeRouteImport } from './routes/opcje'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumWatekIdRouteImport } from './routes/forum.watek.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpcjeRoute = OpcjeRouteImport.update({
  id: '/opcje',
  path: '/opcje',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumRoute,
} as any)
const ForumWatekIdRoute = ForumWatekIdRouteImport.update({
  id: '/watek/$id',
  path: '/watek/$id',
  getParentRoute: () => ForumRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forum': typeof ForumRouteWithChildren
  '/opcje': typeof OpcjeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forum/': typeof ForumIndexRoute
  '/forum/watek/$id': typeof ForumWatekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/opcje': typeof OpcjeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forum': typeof ForumIndexRoute
  '/forum/watek/$id': typeof ForumWatekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forum': typeof ForumRouteWithChildren
  '/opcje': typeof OpcjeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forum/': typeof ForumIndexRoute
  '/forum/watek/$id': typeof ForumWatekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forum'
    | '/opcje'
    | '/sitemap.xml'
    | '/forum/'
    | '/forum/watek/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/opcje' | '/sitemap.xml' | '/forum' | '/forum/watek/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/forum'
    | '/opcje'
    | '/sitemap.xml'
    | '/forum/'
    | '/forum/watek/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ForumRoute: typeof ForumRouteWithChildren
  OpcjeRoute: typeof OpcjeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opcje': {
      id: '/opcje'
      path: '/opcje'
      fullPath: '/opcje'
      preLoaderRoute: typeof OpcjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/watek/$id': {
      id: '/forum/watek/$id'
      path: '/watek/$id'
      fullPath: '/forum/watek/$id'
      preLoaderRoute: typeof ForumWatekIdRouteImport
      parentRoute: typeof ForumRoute
    }
  }
}

interface ForumRouteChildren {
  ForumIndexRoute: typeof ForumIndexRoute
  ForumWatekIdRoute: typeof ForumWatekIdRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumIndexRoute: ForumIndexRoute,
  ForumWatekIdRoute: ForumWatekIdRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ForumRoute: ForumRouteWithChildren,
  OpcjeRoute: OpcjeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
